### ISSUE TITLE
quests issue

### ISSUE THREAD

**Issue by Pixelmidou** [TheNimbleNinja/Project-Equivalence-Issues#52]
the quests are all messed up , starting from version above 6.23.2 , which is the last version where quests are OK

**Comment by TheNimbleNinja** [comment]
wat do you mean screenshots?

**Comment by Pixelmidou** [comment]
this is a picture from 6.23.2 , quests are fine , everything is good .

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a3c4fc0e-13ab-4176-8a69-5fd3ef687f75" />

this a picture form the latest version , quests are all messed up 
( tried all version after 6.23.2 , all of them have messed up quests )

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/95ceda85-cdd0-4b90-bd18-7da54b1e76e2" />

**Comment by Pixelmidou** [comment]
so ? any solution ? or would you push an update to correct it ?
apparently it was ruined when you redid the starting questline in 6.24

**Comment by TheNimbleNinja** [comment]
i fixed the quests anything else :)

**Comment by Pixelmidou** [comment]
nope thx

**Comment by Pixelmidou** [comment]
Hey , it wasn't fixed , there wasn't even any new update pushed to curseforge , the quests are still messed up

**Comment by TheNimbleNinja** [comment]
i did push an update but for wat ever reason its in under review

**Comment by TheNimbleNinja** [comment]
its live now as update 6.26

**Comment by Pixelmidou** [comment]
yup it is fixed thx , when you have time , please provide a server pack
